# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Local_Agent'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TestEngine@1
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)\MQTT-Project-readyapi-project'
    serverUrl: 'http://localhost:8080'
    serverUsername: 'admin'
    serverPassword: 'testengine'
